! ------------------------------------------------------------------------------
! testing CUDA Fortran
! sample code from https://docs.nvidia.com/hpc-sdk/compilers/
! cuda-fortran-prog-guide/index.html#cfpg-cuda-fort-host-dev-code
      module mytests
      contains
      attributes(global) subroutine test1( a )
      integer, device :: a(*)
      i = threadIdx%x
      a(i) = i
      return
      end subroutine test1
      end module mytests
