#! /bin/csh -f

#------------------------------------------------------------------------------
# Get variables from Case XML-files
#------------------------------------------------------------------------------

setenv CASE `./xmlquery CASE --value`
setenv CONFIG_OCN_FILE `./xmlquery CONFIG_OCN_FILE --value`
setenv CASEROOT `./xmlquery CASEROOT --value`
setenv EXEROOT `./xmlquery EXEROOT --value`
setenv OCN_GRID `./xmlquery OCN_GRID --value`
setenv CONFIG_OCN_DIR1 `dirname $CONFIG_OCN_FILE`
setenv NTASKS_OCN `./xmlquery NTASKS_OCN --value` 
setenv DIN_LOC_ROOT `./xmlquery  DIN_LOC_ROOT --value`
setenv RUN_TYPE `./xmlquery RUN_TYPE --value`
setenv CONTINUE_RUN `./xmlquery CONTINUE_RUN --value`
setenv CASEBUILD `./xmlquery CASEBUILD --value`
setenv CCSM_CO2_PPMV `./xmlquery CCSM_CO2_PPMV --value`
setenv OCN_NCPL `./xmlquery OCN_NCPL --value`
setenv BLOM_COUPLING `./xmlquery BLOM_COUPLING --value`
setenv RUNDIR `./xmlquery RUNDIR --value`
setenv BLOM_TRACER_MODULES `./xmlquery BLOM_TRACER_MODULES --value`
setenv BLOM_RIVER_NUTRIENTS `./xmlquery BLOM_RIVER_NUTRIENTS --value`
setenv BLOM_N_DEPOSITION `./xmlquery BLOM_N_DEPOSITION --value`
setenv BLOM_N_DEP_FILE `./xmlquery BLOM_N_DEP_FILE --value`
setenv RUN_STARTDATE `./xmlquery RUN_STARTDATE --value`
echo $CASE ${EXEROOT} $CASEBUILD
cd $EXEROOT/ocn/obj
setenv CONFIG_OCN_DIR $CONFIG_OCN_DIR1/../

#------------------------------------------------------------------------------
# Make dimensions.F
#------------------------------------------------------------------------------

set dimdir = $EXEROOT/ocn/obj/dimensions
mkdir -p $dimdir
set kdm = `cat $CONFIG_OCN_DIR/bld/$OCN_GRID/kdm`
$CONFIG_OCN_DIR/bld/blom_dimensions -n $NTASKS_OCN -k $kdm -d $CONFIG_OCN_DIR/bld/$OCN_GRID || exit -1
set recompile = FALSE
cmp -s dimensions.F $dimdir/dimensions.F || set recompile = TRUE
echo $PWD
echo $recompile
if ($recompile == 'TRUE') then
  mv dimensions.F $dimdir
else
  rm dimensions.F
endif

#------------------------------------------------------------------------------
# Set RUN_TYPE to 'continue' if CONTINUE_RUN equals TRUE
#------------------------------------------------------------------------------

if ($CONTINUE_RUN == TRUE) then
  setenv RUN_TYPE continue
endif

#------------------------------------------------------------------------------
# Generate blom.input_data_list
#------------------------------------------------------------------------------

if      ($OCN_GRID == gx1v5) then
  setenv INPUTPATH $DIN_LOC_ROOT/ocn/blom/$OCN_GRID/20091216
else if ($OCN_GRID == gx1v6) then
  setenv INPUTPATH $DIN_LOC_ROOT/ocn/blom/$OCN_GRID/20101119
else if ($OCN_GRID == gx3v7) then
  setenv INPUTPATH $DIN_LOC_ROOT/ocn/blom/$OCN_GRID/20110921
else if ($OCN_GRID == tnx2v1) then
  setenv INPUTPATH $DIN_LOC_ROOT/ocn/blom/$OCN_GRID/20130206
else if ($OCN_GRID == tnx1.5v1) then
  setenv INPUTPATH $DIN_LOC_ROOT/ocn/blom/$OCN_GRID/20131011
else if ($OCN_GRID == tnx1v1) then
  setenv INPUTPATH $DIN_LOC_ROOT/ocn/blom/$OCN_GRID/20120120
else if ($OCN_GRID == tnx1v3) then
  setenv INPUTPATH $DIN_LOC_ROOT/ocn/blom/$OCN_GRID/20170612
else if ($OCN_GRID == tnx1v4) then
  setenv INPUTPATH $DIN_LOC_ROOT/ocn/blom/$OCN_GRID/20170601
else if ($OCN_GRID == tnx0.25v1) then
  setenv INPUTPATH $DIN_LOC_ROOT/ocn/blom/$OCN_GRID/20130930
else if ($OCN_GRID == tnx0.25v3) then
  setenv INPUTPATH $DIN_LOC_ROOT/ocn/blom/$OCN_GRID/20170623
else if ($OCN_GRID == tnx0.25v4) then
  setenv INPUTPATH $DIN_LOC_ROOT/ocn/blom/$OCN_GRID/20170619
else
  echo "$0 ERROR: Cannot deal with GRID = $OCN_GRID "
  exit -1
endif
echo $CASEBUILD
cat > $CASEBUILD/blom.input_data_list << EOF1
grid_file = $INPUTPATH/grid.nc
ncep_landmask_file = $INPUTPATH/land.sfc.gauss.nc
ncep_height_file = $INPUTPATH/hgt.sfc.nc
ice_clim_file = $INPUTPATH/icec_1968-1996.uf
sst_clim_file = $INPUTPATH/skt_1968-1996.uf
tidal_dissipation_file = $INPUTPATH/tidal_dissipation.nc
meridional_transport_index_file = $INPUTPATH/mertraindex.dat
meridional_transport_basin_file = $INPUTPATH/mertraoceans.dat
section_index_file = $INPUTPATH/secindex.dat
EOF1
if ($RUN_TYPE == startup)  then
cat >> $CASEBUILD/blom.input_data_list << EOF1
inicon_file = $INPUTPATH/inicon.nc
EOF1
endif
set tracers = (`echo $BLOM_TRACER_MODULES`)
set rivnutr = (`echo $BLOM_RIVER_NUTRIENTS`)
set ndep    = (`echo $BLOM_N_DEPOSITION`)
foreach module ($tracers)
  if ($module == ecosys) then
cat >> $CASEBUILD/blom.input_data_list << EOF1
dust_file = $INPUTPATH/INPDUST_mhw.nc
EOF1
    if ($rivnutr == TRUE) then
cat >> $CASEBUILD/blom.input_data_list << EOF1
river_file = $INPUTPATH/river_nutrients_GNEWS2000.nc
EOF1
    endif
    if ($ndep == TRUE) then
cat >> $CASEBUILD/blom.input_data_list << EOF1
n_deposition_file = $INPUTPATH/$BLOM_N_DEP_FILE
EOF1
    endif
  endif
end

#------------------------------------------------------------------------------
# Set namelist variables
#------------------------------------------------------------------------------

# set LIMITS defaults
set ICFILE   = "'inicon.nc'"
set BACLIN   = 1800.
set BATROP   = 36.
set MDV2HI   = 2.
set MDV2LO   = .4
set MDV4HI   = 0.
set MDV4LO   = 0.
set MDC2HI   = 5000.e4
set MDC2LO   = 300.e4
set VSC2HI   = .5
set VSC2LO   = .5
set VSC4HI   = 0.
set VSC4LO   = 0.
set CBAR     = 5.
set CB       = .002
set CWBDTS   = 5.e-5
set CWBDLS   = 25.
set MOMMTH   = "'enscon'"
set EITMTH   = "'gm'"
set EDRITP   = "'large scale'"
set BMCMTH   = "'uc'"
set RMPMTH   = "'eitvel'"
set EDWMTH   = "'smooth'"
set MLRTTP   = "'constant'"
set EDSPRS   = .true.
set EGC      = 0.85
set EGGAM    = 200.
set EGLSMN   = 4000.e2
set EGMNDF   = 100.e4
set EGMXDF   = 1500.e4
set EGIDFQ   = 1.
set RI0      = 1.2
set RM0      = 1.2
set RM5      = 0.
set CE       = .06
set BDMTYP   = 2
set BDMC1    = 5.e-4
set BDMC2    = .1
set TKEPF    = .006
set NIWGF    = 0.
set NIWBF    = .35
set NIWLF    = .5
set SWAMTH   = "'jerlov'"
set JWTYPE   = 3
set CHLOPT   = "'climatology'"
set TRXDAY   = 0.
set SRXDAY   = 0.
set TRXDPT   = 1.
set SRXDPT   = 1.
set TRXLIM   = 1.5
set SRXLIM   = .5
set APTFLX   = .false.
set APSFLX   = .false.
set DITFLX   = .false.
set DISFLX   = .false.
set SRXBAL   = .false.
set SRXSRC   = "'CORE'"
set SMTFRC   = .true.
set SPRFAC   = .false.
set RSTFRQ   =  1
set RSTFMT   =  1
set RSTCMP   =  0 
set IOTYPE   =  0 
# set BGCNML defaults
set ATM_CO2  = $CCSM_CO2_PPMV
if ($rivnutr == TRUE) then
  set DO_RIVINPT = .true.
else
  set DO_RIVINPT   = .false.
endif
if ($ndep == TRUE) then
  set DO_NDEP   = .true.
  set NDEPFNAME = $BLOM_N_DEP_FILE
else
  set DO_NDEP   = .false.
  set NDEPFNAME = "''"
endif
# set DIAPHY defaults 
set GLB_FNAMETAG = "'hd','hm','hy'"  
set GLB_AVEPERIO =  '1,  30, 365'
set GLB_FILEFREQ = '30,  30, 365'
set GLB_COMPFLAG =  '0,   0,   0'
set GLB_NCFORMAT =  '0,   0,   0'
set H2D_ABSWND   =  '0,   4,   0'
set H2D_ALB      =  '0,   0,   0'
set H2D_BTMSTR   =  '0,   4,   0'
set H2D_BRNFLX   =  '0,   4,   0'
set H2D_BRNPD    =  '0,   4,   0'
set H2D_DFL      =  '0,   0,   0'
set H2D_EVA      =  '0,   4,   0'
set H2D_FICE     =  '0,   4,   0'
set H2D_FMLTFZ   =  '0,   4,   0'
set H2D_HICE     =  '0,   0,   0'
set H2D_HMLTFZ   =  '0,   4,   0'
set H2D_HSNW     =  '0,   0,   0'
set H2D_IAGE     =  '0,   0,   0'
set H2D_IDKEDT   =  '0,   4,   0'
set H2D_LIP      =  '0,   4,   0'
set H2D_MAXMLD   =  '4,   4,   0'
set H2D_MLD      =  '0,   4,   0'
set H2D_MLDU     =  '0,   0,   0'
set H2D_MLDV     =  '0,   0,   0'
set H2D_MLTS     =  '4,   4,   0'
set H2D_MLTSMN   =  '0,   4,   0'
set H2D_MLTSMX   =  '0,   4,   0'
set H2D_MLTSSQ   =  '0,   4,   0'
set H2D_MTKEUS   =  '0,   4,   0'
set H2D_MTKENI   =  '0,   4,   0'
set H2D_MTKEBF   =  '0,   4,   0'
set H2D_MTKERS   =  '0,   4,   0'
set H2D_MTKEPE   =  '0,   4,   0'
set H2D_MTKEKE   =  '0,   4,   0'
set H2D_MTY      =  '0,   4,   0'
set H2D_MXLU     =  '0,   4,   0'
set H2D_MXLV     =  '0,   4,   0'
set H2D_NSF      =  '0,   4,   0'
set H2D_PBOT     =  '0,   4,   0'
set H2D_PSRF     =  '0,   4,   0'
set H2D_RFIFLX   =  '0,   4,   0'
set H2D_RNFFLX   =  '0,   4,   0'
set H2D_SALFLX   =  '0,   4,   0'
set H2D_SALRLX   =  '0,   4,   0'
set H2D_SBOT     =  '0,   4,   0'
set H2D_SEALV    =  '4,   4,   0'
set H2D_SLVSQ    =  '0,   4,   0'
set H2D_SFL      =  '0,   4,   0'
set H2D_SOP      =  '0,   4,   0'
set H2D_SIGMX    =  '0,   4,   0'
set H2D_SSS      =  '4,   4,   0'
set H2D_SSSSQ    =  '4,   4,   0'
set H2D_SST      =  '4,   4,   0'
set H2D_SSTSQ    =  '4,   4,   0'
set H2D_SURFLX   =  '0,   4,   0'
set H2D_SURRLX   =  '0,   4,   0'
set H2D_SWA      =  '0,   4,   0'
set H2D_T20D     =  '4,   4,   0'
set H2D_TAUX     =  '0,   4,   0'
set H2D_TAUY     =  '0,   4,   0'
set H2D_TBOT     =  '0,   4,   0'
set H2D_TICE     =  '0,   0,   0'
set H2D_TSRF     =  '0,   0,   0'
set H2D_UB       =  '0,   4,   0'
set H2D_UICE     =  '0,   0,   0'
set H2D_USTAR    =  '0,   4,   0'
set H2D_USTAR3   =  '0,   4,   0'
set H2D_VB       =  '0,   4,   0'
set H2D_VICE     =  '0,   0,   0'
set H2D_ZTX      =  '0,   4,   0'
set LYR_BFSQ     =  '0,   4,   0'
set LYR_DIFDIA   =  '0,   4,   0'
set LYR_DIFINT   =  '0,   4,   0'
set LYR_DIFISO   =  '0,   4,   0'
set LYR_DP       =  '0,   4,   0'
set LYR_DZ       =  '0,   4,   0'
set LYR_SALN     =  '0,   4,   0'
set LYR_TEMP     =  '0,   4,   0'
set LYR_TRC      =  '0,   0,   0'
set LYR_UFLX     =  '0,   4,   0'
set LYR_UTFLX    =  '0,   4,   0'
set LYR_USFLX    =  '0,   4,   0'
set LYR_UMFLTD   =  '0,   0,   4'
set LYR_UTFLTD   =  '0,   0,   4'
set LYR_UTFLLD   =  '0,   0,   4'
set LYR_USFLTD   =  '0,   0,   4'
set LYR_USFLLD   =  '0,   0,   4'
set LYR_UVEL     =  '0,   4,   0'
set LYR_VFLX     =  '0,   4,   0'
set LYR_VTFLX    =  '0,   4,   0'
set LYR_VSFLX    =  '0,   4,   0'
set LYR_VMFLTD   =  '0,   4,   0'
set LYR_VTFLTD   =  '0,   4,   0'
set LYR_VTFLLD   =  '0,   4,   0'
set LYR_VSFLTD   =  '0,   4,   0'
set LYR_VSFLLD   =  '0,   4,   0'
set LYR_VVEL     =  '0,   4,   0'
set LYR_WFLX     =  '0,   4,   0'
set LYR_WFLX2    =  '0,   4,   0'
set LYR_PV       =  '0,   4,   0'
set LYR_TKE      =  '0,   4,   0'
set LYR_GLS_PSI  =  '0,   4,   0'
set LYR_IDLAGE   =  '0,   4,   0'
set LVL_BFSQ     =  '0,   4,   0'
set LVL_DIFDIA   =  '0,   4,   0'
set LVL_DIFINT   =  '0,   4,   0'
set LVL_DIFISO   =  '0,   4,   0'
set LVL_DZ       =  '0,   4,   0'
set LVL_SALN     =  '0,   4,   0'
set LVL_TEMP     =  '0,   4,   0'
set LVL_TRC      =  '0,   0,   0'
set LVL_UFLX     =  '0,   4,   0'
set LVL_UTFLX    =  '0,   4,   0'
set LVL_USFLX    =  '0,   4,   0'
set LVL_UMFLTD   =  '0,   0,   4'
set LVL_UTFLTD   =  '0,   0,   4'
set LVL_UTFLLD   =  '0,   0,   4'
set LVL_USFLTD   =  '0,   0,   4'
set LVL_USFLLD   =  '0,   0,   4'
set LVL_UVEL     =  '0,   4,   0'
set LVL_VFLX     =  '0,   4,   0'
set LVL_VTFLX    =  '0,   4,   0'
set LVL_VSFLX    =  '0,   4,   0'
set LVL_VMFLTD   =  '0,   0,   4'
set LVL_VTFLTD   =  '0,   0,   4'
set LVL_VTFLLD   =  '0,   0,   4'
set LVL_VSFLTD   =  '0,   0,   4'
set LVL_VSFLLD   =  '0,   0,   4'
set LVL_VVEL     =  '0,   4,   0'
set LVL_WFLX     =  '0,   4,   0'
set LVL_WFLX2    =  '0,   4,   0'
set LVL_PV       =  '0,   4,   0'
set LVL_TKE      =  '0,   4,   0'
set LVL_GLS_PSI  =  '0,   4,   0'
set LVL_IDLAGE   =  '0,   4,   0'
set MSC_MMFLXL   =  '0,   4,   0'
set MSC_MMFLXD   =  '0,   4,   0'
set MSC_MMFTDL   =  '0,   4,   0'
set MSC_MMFTDD   =  '0,   4,   0'
set MSC_MHFLX    =  '0,   4,   0'
set MSC_MHFTD    =  '0,   4,   0'
set MSC_MHFLD    =  '0,   4,   0'
set MSC_MSFLX    =  '0,   4,   0'
set MSC_MSFTD    =  '0,   4,   0'
set MSC_MSFLD    =  '0,   4,   0'
set MSC_VOLTR    =  '0,   4,   0'
set MSC_MASSGS   =  '0,   4,   0'
set MSC_VOLGS    =  '0,   4,   0'
set MSC_SALNGA   =  '0,   4,   0'
set MSC_TEMPGA   =  '0,   4,   0'
set MSC_SSSGA    =  '0,   4,   0'
set MSC_SSTGA    =  '0,   4,   0'
# set DIABGC defaults
set BGC_FNAMETAG  = "'hbgcd','hbgcm','hbgcy'"
set BGC_AVEPERIO  = '1,30,365'
set BGC_FILEFREQ  = '30,30,365'
set BGC_COMPFLAG  = '0, 0, 0'
set BGC_NCFORMAT  = '0, 0, 0'
set BGC_INVENTORY = '0, 1, 0'
set SRF_PHOSPH    = '0, 2, 2'
set SRF_OXYGEN    = '0, 2, 2'    
set SRF_IRON      = '0, 2, 2'   
set SRF_ANO3      = '0, 2, 2'
set SRF_ALKALI    = '4, 2, 2'
set SRF_SILICA    = '0, 2, 2' 
set SRF_DIC       = '4, 2, 2' 
set SRF_PHYTO     = '4, 2, 2' 
set SRF_EXPORT    = '0, 2, 2' 
set SRF_EXPOSI    = '0, 2, 2' 
set SRF_EXPOCA    = '0, 2, 2' 
set SRF_KWCO2     = '0, 2, 2' 
set SRF_PCO2      = '0, 2, 2' 
set SRF_CO2FXD    = '4, 2, 2' 
set SRF_CO2FXU    = '4, 2, 2' 
set SRF_OXFLUX    = '0, 2, 2' 
set SRF_NIFLUX    = '0, 2, 2' 
set SRF_N2OFX     = '0, 0, 2' 
set SRF_DMSFLUX   = '0, 2, 2' 
set SRF_DMS       = '0, 2, 2' 
set SRF_DMSPROD   = '0, 2, 2' 
set SRF_DMS_BAC   = '0, 2, 2' 
set SRF_DMS_UV    = '0, 2, 2' 
set SRF_ATMCO2    = '0, 2, 2' 
set SRF_ATMO2     = '0, 2, 2' 
set SRF_ATMN2     = '0, 2, 2' 
set SRF_NATDIC    = '0, 2, 2'
set SRF_NATALKALI = '0, 2, 2'
set SRF_NATPCO2   = '0, 2, 2'
set SRF_NATCO2FX  = '0, 2, 2'
set SRF_CO213FXD  = '0, 2, 2' 
set SRF_CO213FXU  = '0, 2, 2' 
set SRF_CO214FXD  = '0, 2, 2' 
set SRF_CO214FXU  = '0, 2, 2' 
set SRF_CFC11     = '0, 2, 2' 
set SRF_CFC12     = '0, 2, 2' 
set SRF_SF6       = '0, 2, 2' 
set INT_PHOSY     = '4, 2, 2' 
set INT_NFIX      = '0, 2, 2' 
set INT_DNIT      = '0, 2, 2' 
set FLX_CAR0100   = '0, 2, 2'
set FLX_CAR0500   = '0, 2, 2'
set FLX_CAR1000   = '0, 2, 2'
set FLX_CAR2000   = '0, 2, 2'
set FLX_CAR4000   = '0, 2, 2'
set FLX_CAR_BOT   = '0, 2, 2'
set FLX_BSI0100   = '0, 2, 2'
set FLX_BSI0500   = '0, 2, 2'
set FLX_BSI1000   = '0, 2, 2'
set FLX_BSI2000   = '0, 2, 2'
set FLX_BSI4000   = '0, 2, 2'
set FLX_BSI_BOT   = '0, 2, 2'
set FLX_CAL0100   = '0, 2, 2'
set FLX_CAL0500   = '0, 2, 2'
set FLX_CAL1000   = '0, 2, 2'
set FLX_CAL2000   = '0, 2, 2'
set FLX_CAL4000   = '0, 2, 2'
set FLX_CAL_BOT   = '0, 2, 2'
set LYR_PHYTO     = '0, 0, 2' 
set LYR_GRAZER    = '0, 0, 2' 
set LYR_DOC       = '0, 0, 2' 
set LYR_PHOSY     = '0, 0, 2' 
set LYR_PHOSPH    = '0, 0, 2' 
set LYR_OXYGEN    = '0, 0, 4' 
set LYR_IRON      = '0, 0, 2'
set LYR_ANO3      = '0, 0, 2'
set LYR_ALKALI    = '0, 0, 2'
set LYR_SILICA    = '0, 0, 2'
set LYR_DIC       = '0, 0, 2'
set LYR_POC       = '0, 0, 2'
set LYR_CALC      = '0, 0, 2'
set LYR_OPAL      = '0, 0, 2'
set LYR_CO3       = '0, 0, 2'
set LYR_N2O       = '0, 0, 0'
set LYR_PH        = '0, 0, 2'
set LYR_OMEGAC    = '0, 0, 2'
set LYR_OMEGAA    = '0, 0, 2'
set LYR_PREFO2    = '0, 0, 4'
set LYR_O2SAT     = '0, 0, 4'
set LYR_PREFPO4   = '0, 0, 2'
set LYR_PREFALK   = '0, 0, 2'
set LYR_PREFDIC   = '0, 0, 2'
set LYR_DICSAT    = '0, 0, 2'
set LYR_NATDIC    = '0, 0, 2'
set LYR_NATALKALI = '0, 0, 2'
set LYR_NATCO3    = '0, 0, 2'
set LYR_NATCALC   = '0, 0, 2'
set LYR_NATPH     = '0, 0, 2'
set LYR_NATOMEGAC = '0, 0, 2'
set LYR_NATOMEGAA = '0, 0, 2'
set LYR_DIC13     = '0, 0, 2'
set LYR_DIC14     = '0, 0, 2'
set LYR_D13C      = '0, 0, 2'
set LYR_D14C      = '0, 0, 2'
set LYR_BIGD14C   = '0, 0, 2'
set LYR_POC13     = '0, 0, 2'
set LYR_DOC13     = '0, 0, 2'
set LYR_CALC13    = '0, 0, 2'
set LYR_PHYTO13   = '0, 0, 2'
set LYR_GRAZER13  = '0, 0, 2'
set LYR_CFC11     = '0, 0, 2'
set LYR_CFC12     = '0, 0, 2'
set LYR_SF6       = '0, 0, 2'
set LYR_NOS       = '0, 0, 2'
set LYR_WPHY      = '0, 0, 2'
set LYR_WNOS      = '0, 0, 2'
set LYR_EPS       = '0, 0, 0'
set LYR_ASIZE     = '0, 0, 0'
set BGC_DP        = '0, 2, 2'
set LVL_PHYTO     = '0, 2, 2'
set LVL_GRAZER    = '0, 2, 2'
set LVL_DOC       = '0, 2, 2'
set LVL_PHOSY     = '0, 2, 2'
set LVL_PHOSPH    = '0, 2, 2'
set LVL_OXYGEN    = '0, 4, 4'
set LVL_IRON      = '0, 2, 2'
set LVL_ANO3      = '0, 2, 2'
set LVL_ALKALI    = '0, 2, 2'
set LVL_SILICA    = '0, 2, 2'
set LVL_DIC       = '0, 2, 2'
set LVL_POC       = '0, 2, 2'
set LVL_CALC      = '0, 2, 2'
set LVL_OPAL      = '0, 2, 2'
set LVL_CO3       = '0, 2, 2'
set LVL_N2O       = '0, 0, 2'
set LVL_PH        = '0, 2, 2'
set LVL_OMEGAC    = '0, 2, 2'
set LVL_OMEGAA    = '0, 2, 2'
set LVL_PREFO2    = '0, 4, 4'
set LVL_O2SAT     = '0, 4, 4'
set LVL_PREFPO4   = '0, 2, 2'
set LVL_PREFALK   = '0, 2, 2'
set LVL_PREFDIC   = '0, 2, 2'
set LVL_DICSAT    = '0, 2, 2'
set LVL_NATDIC    = '0, 2, 2'
set LVL_NATALKALI = '0, 2, 2'
set LVL_NATCO3    = '0, 2, 2'
set LVL_NATCALC   = '0, 2, 2'
set LVL_NATPH     = '0, 2, 2'
set LVL_NATOMEGAC = '0, 2, 2'
set LVL_NATOMEGAA = '0, 2, 2'
set LVL_DIC13     = '0, 2, 2'
set LVL_DIC14     = '0, 2, 2'
set LVL_D13C      = '0, 2, 2'
set LVL_POC13     = '0, 2, 2'
set LVL_DOC13     = '0, 2, 2'
set LVL_CALC13    = '0, 2, 2'
set LVL_PHYTO13   = '0, 2, 2'
set LVL_GRAZER13  = '0, 2, 2'
set LVL_CFC11     = '0, 2, 2'
set LVL_CFC12     = '0, 2, 2'
set LVL_SF6       = '0, 2, 2'
set LVL_NOS       = '0, 2, 2'
set LVL_WPHY      = '0, 2, 2'
set LVL_WNOS      = '0, 2, 2'
set LVL_EPS       = '0, 0, 0'
set LVL_ASIZE     = '0, 0, 0'
set SDM_POWAIC    = '0, 0, 2'
set SDM_POWAAL    = '0, 0, 2'
set SDM_POWAPH    = '0, 0, 2'
set SDM_POWAOX    = '0, 0, 2'
set SDM_POWN2     = '0, 0, 2'
set SDM_POWNO3    = '0, 0, 2'
set SDM_POWASI    = '0, 0, 2'
set SDM_SSSO12    = '0, 0, 2'
set SDM_SSSSIL    = '0, 0, 2'
set SDM_SSSC12    = '0, 0, 2'
set SDM_SSSTER    = '0, 0, 2'
set BUR_SSSO12    = '0, 0, 2'
set BUR_SSSSIL    = '0, 0, 2'
set BUR_SSSC12    = '0, 0, 2'
set BUR_SSSTER    = '0, 0, 2'

#set IYEAR0   = `echo $RUN_STARTDATE | cut -c1-4  | sed -e 's/^0*//'`
#set IMONTH0  = `echo $RUN_STARTDATE | cut -c6-7  | sed -e 's/^0*//'`
#set IDAY0    = `echo $RUN_STARTDATE | cut -c9-10 | sed -e 's/^0*//'`
set YEAR0   = `echo $RUN_STARTDATE | cut -c1-4 `
set MONTH0  = `echo $RUN_STARTDATE | cut -c6-7 `
set DAY0    = `echo $RUN_STARTDATE | cut -c9-10`

if ($BLOM_COUPLING  =~ *partial*) then
  set SRXDAY = 6.
  set SPRFAC = .true.
  set SRXBAL = .true.
endif

if ($OCN_GRID == gx1v5 || $OCN_GRID == gx1v6) then
  set BACLIN = 1800.
  set BATROP = 36.
else if ($OCN_GRID == gx3v7) then
  set BACLIN = 3600.
  set BATROP = 72.
else if ($OCN_GRID == tnx2v1 ) then
  set BACLIN = 4800.
  set BATROP = 96.
  set EGC    = 0.5
  set EGMXDF = 1000.e4
  set CWMTAG = "'Gibraltar','Gibraltar'"
  set CWMEDG = "        'u',        'u'"
  set CWMI   = "         53,         54"
  set CWMJ   = "        137,        137"
  set CWMWTH = "      30.e3,      30.e3"
else if ($OCN_GRID == tnx1.5v1 ) then
  set BACLIN = 4800.
  set BATROP = 96.
  set EGC    = 0.5
  set EGMXDF = 1000.e4
else if ($OCN_GRID == tnx1v1 || $OCN_GRID == tnx1v3 || $OCN_GRID == tnx1v4) then
  if ($OCN_NCPL == 24) then
    set BACLIN = 3600.
    set BATROP = 60.
    set CWBDTS = .75e-4
    set CE     = .5
    set NIWGF  = .4
    set SMTFRC = .false.
  else
    set BACLIN = 3200.
    set BATROP = 64.
  endif
  set CWMTAG = "'Gibraltar','Gibraltar'"
  set CWMEDG = "        'u',        'u'"
  set CWMI   = "        105,        106"
  set CWMJ   = "        273,        273"
  set CWMWTH = "      30.e3,      30.e3"
else if ($OCN_GRID == tnx0.25v1 || $OCN_GRID == tnx0.25v3 || $OCN_GRID == tnx0.25v4) then
  set BACLIN = 900.
  set BATROP = 15.
  set MDV2HI = .15
  set MDV2LO = .15
  set VSC2HI = .15
  set VSC2LO = .15
  set VSC4HI = 0.0625
  set VSC4LO = 0.0625
  set MDC2HI = 300.e4
  set CWBDTS = 0.75e-4
  set CWBDLS = 25.
  set EDWMTH = "'step'"
  set EGC    = 0.85
  set EGMXDF = 1500.e4
  set CE     = 1.0
  set GLB_NCFORMAT =  '1,   1,   1'
  set BGC_NCFORMAT  = '1,   1,   1'
else
  echo "$0 ERROR: Cannot deal with GRID = $OCN_GRID "
  exit -1
endif
echo $CASEROOT
source $CASEROOT/user_nl_blom
#------------------------------------------------------------------------------
# Create resolved namelist
#------------------------------------------------------------------------------

cat >! $RUNDIR/ocn_in << EOF1
! LIMITS NAMELIST
!
! CONTENTS:
!
! NDAY1    : First day of integration (i)
! NDAY2    : Last day of integration (i)
! IDATE    : Model date in YYYYMMDD (i)
! IDATE0   : Initial experiment date in YYYYMMDD (i)
! RUNID    : Experiment name (a)
! EXPCNF   : Experiment configuration (a)
! RUNTYP   : CESM run type (a)
! ICFILE   : Name of file containing initial conditions, that is either
!            a valid restart file or 'inicon.nc' if climatological based
!            initial conditions are desired (a)
! BACLIN   : Baroclinic time step (sec) (f)
! BATROP   : Barotropic time step (sec) (f)
! MDV2HI   : Laplacian diffusion velocity for momentum dissipation (cm/s) (f)
! MDV2LO   : Laplacian diffusion velocity for momentum dissipation (cm/s) (f)
! MDV4HI   : Biharmonic diffusion velocity for momentum dissipation (cm/s) (f)
! MDV4LO   : Biharmonic diffusion velocity for momentum dissipation (cm/s) (f)
! MDC2HI   : Laplacian diffusivity for momentum dissipation (cm**2/s) (f)
! MDC2LO   : Laplacian diffusivity for momentum dissipation (cm**2/s) (f)
! VSC2HI   : Parameter in deformation-dependent Laplacian viscosity (f)
! VSC2LO   : Parameter in deformation-dependent Laplacian viscosity (f)
! VSC4HI   : Parameter in deformation-dependent Biharmonic viscosity (f)
! VSC4LO   : Parameter in deformation-dependent Biharmonic viscosity (f)
! CBAR     : rms flow speed for linear bottom friction law (cm/s) (f)
! CB       : Nondiemnsional coefficient of quadratic bottom friction (f)
! CWBDTS   : Coastal wave breaking damping resiprocal time scale (1/s) (f)
! CWBDLS   : Coastal wave breaking damping length scale (m) (f)
! MOMMTH   : Momentum equation discretization method. Valid methods:
!            'enscon' (Sadourny (1975) enstrophy conserving), 'enecon'
!            (Sadourny (1975) energy conserving), 'enedis' (Sadourny
!            (1975) energy conserving with some dissipation) (a)
! EITMTH   : Eddy-induced transport parameterization method. Valid
!            methods: 'intdif', 'gm' (a)
! EDRITP   : Type of Richardson number used in eddy diffusivity
!            computation. Valid types: 'shear', 'large scale' (a)
! BMCMTH   : Baroclinic mass flux correction method. Valid methods:
!            'uc' (upstream column), 'dluc' (depth limited upstream
!            column) (a)
! RMPMTH   : Method of applying eddy-induced transport in the remap
!            transport algorithm. Valid methods: 'eitvel', 'eitflx' (a)
! EDWMTH   : Method to estimate eddy diffusivity weight as a function of
!            the ration of Rossby radius of deformation to the
!            horizontal grid spacing. Valid methods: 'smooth', 'step' (a)
! MLRTTP   : Type of mixed layer restratification time scale. Valid
!            types: 'variable', 'constant', 'limited' (a)
! EDSPRS   : Apply eddy mixing suppression away from steering level (l)
! EGC      : Parameter c in Eden and Greatbatch (2008) parameterization (f)
! EGGAM    : Parameter gamma in E. & G. (2008) param. (f)
! EGLSMN   : Minimum eddy length scale in  E. & G. (2008) param. (cm) (f)
! EGMNDF   : Minimum diffusivity in E. & G. (2008) param. (cm**2/s) (f)
! EGMXDF   : Maximum diffusivity in E. & G. (2008) param. (cm**2/s) (f)
! EGIDFQ   : Factor relating the isopycnal diffusivity to the layer
!            interface diffusivity in the Eden and Greatbatch (2008)
!            parameterization. egidfq=difint/difiso () (f)
! RI0      : Critical gradient richardson number for shear driven
!            vertical mixing () (f)
! RM0      : Efficiency factor of wind TKE generation in the Oberhuber
!            (1993) TKE closure () (f)
! RM5      : Efficiency factor of TKE generation by momentum
!            entrainment in the Oberhuber (1993) TKE closure () (f)
! CE       : Efficiency factor for the restratification by mixed layer
!            eddies (Fox-Kemper et al., 2008) () (f)
! BDMTYP   : Type of background diapycnal mixing. If bdmtyp=1 the
!            background diffusivity is a constant divided by the
!            Brunt-Vaisala frequency, if bdmtyp=2 the background
!            diffusivity is constant () (i)
! BDMC1    : Background diapycnal diffusivity times buoyancy frequency
!            frequency (cm**2/s**2) (f)
! BDMC2    : Background diapycnal diffusivity (cm**2/s) (f)
! TKEPF    : Fraction of surface TKE that penetrates beneath mixed layer
!            () (f)
! NIWGF    : Global factor applied to the energy input by near-intertial
!            motions () (f)
! NIWBF    : Fraction of near-inertial energy dissipated in the boundary
!            layer () (f)
! NIWLF    : Fraction of near-inertial energy dissipated locally beneath
!            the boundary layer () (f)
! SWAMTH   : Shortwave radiation absorption method. Valid methods:
!            'top-layer', 'jerlov', 'chlorophyll' (a)
! JWTYPE   : Number indicating the Jerlov (1968) water type (i)
! CHLOPT   : Chlorophyll concentration option. Valid options:
!            'climatology' (a)
! TRXDAY   : e-folding time scale (days) for SST relax., if 0 no relax. (f)
! SRXDAY   : e-folding time scale (days) for SSS relax., if 0 no relax. (f)
! TRXDPT   : Maximum mixed layer depth for e-folding SST relaxation (m) (f)
! SRXDPT   : Maximum mixed layer depth for e-folding SSS relaxation (m) (f)
! TRXLIM   : Max. absolute value of SST difference in relaxation (degC) (f)
! SRXLIM   : Max. absolute value of SSS difference in relaxation (psu) (f)
! APTFLX   : Apply diagnosed heat flux flag (l)
! APSFLX   : Apply diagnosed freshwater flux flag (l)
! DITFLX   : Diagnose heat flux flag (l)
! DISFLX   : Diagnose freshwater flux flag (l)
! SRXBAL   : Balance the SSS relaxation (l)
! SRXSRC   : SSS climatology used for relax. Valid opts. 'PHC3.0' or 'CORE' (a)
! SMTFRC   : Smooth CESM forcing (l)
! SPRFAC   : Send precipitation/runoff factor to CESM coupler (l)
! PATH     : Path to input files (a)
! ATM_PATH : Path to synoptic NCEP fields (a)
! RSTFRQ   : Restart frequency in days (30=1month,365=1year) (i)
! RSTFMT   : Format of restart file (valid arguments are 0 for classic,
!            1 for 64-bit offset and 2 for netcdf4/hdf5 format) (i)
! RSTCMP   : Compression flag for restart file (i)
! IOTYPE   : 0 = netcdf, 1 = pnetcdf
&LIMITS
  NDAY1    = 0,
  NDAY2    = 0,
  IDATE    = ${YEAR0}${MONTH0}${DAY0},
  IDATE0   = ${YEAR0}${MONTH0}${DAY0},
  RUNID    = 'xxxx',
  EXPCNF   = 'cesm',
  RUNTYP   = "${RUN_TYPE}",
  ICFILE   = ${ICFILE},
  BACLIN   = ${BACLIN},
  BATROP   = ${BATROP},
  MDV2HI   = ${MDV2HI},
  MDV2LO   = ${MDV2LO},
  MDV4HI   = ${MDV4HI},
  MDV4LO   = ${MDV4LO},
  MDC2HI   = ${MDC2HI},
  MDC2LO   = ${MDC2LO},
  VSC2HI   = ${VSC2HI},
  VSC2LO   = ${VSC2LO},
  VSC4HI   = ${VSC4HI},
  VSC4LO   = ${VSC4LO},
  CBAR     = ${CBAR},
  CB       = ${CB},
  CWBDTS   = ${CWBDTS},
  CWBDLS   = ${CWBDLS},
  MOMMTH   = ${MOMMTH},
  EITMTH   = ${EITMTH},
  EDRITP   = ${EDRITP},
  BMCMTH   = ${BMCMTH},
  RMPMTH   = ${RMPMTH},
  EDWMTH   = ${EDWMTH},
  MLRTTP   = ${MLRTTP},
  EDSPRS   = ${EDSPRS},
  EGC      = ${EGC},
  EGGAM    = ${EGGAM},
  EGLSMN   = ${EGLSMN},
  EGMNDF   = ${EGMNDF},
  EGMXDF   = ${EGMXDF},
  EGIDFQ   = ${EGIDFQ},
  RI0      = ${RI0},
  RM0      = ${RM0},
  RM5      = ${RM5},
  CE       = ${CE},
  BDMTYP   = ${BDMTYP},
  BDMC1    = ${BDMC1},
  BDMC2    = ${BDMC2},
  TKEPF    = ${TKEPF},
  NIWGF    = ${NIWGF},
  NIWBF    = ${NIWBF},
  NIWLF    = ${NIWLF},
  SWAMTH   = ${SWAMTH},
  JWTYPE   = ${JWTYPE},
  CHLOPT   = ${CHLOPT},
  TRXDAY   = ${TRXDAY},
  SRXDAY   = ${SRXDAY},
  TRXDPT   = ${TRXDPT},
  SRXDPT   = ${SRXDPT},
  TRXLIM   = ${TRXLIM},
  SRXLIM   = ${SRXLIM},
  APTFLX   = ${APTFLX},
  APSFLX   = ${APSFLX},
  DITFLX   = ${DITFLX},
  DISFLX   = ${DISFLX},
  SRXBAL   = ${SRXBAL},
  SRXSRC   = ${SRXSRC},
  SMTFRC   = ${SMTFRC},
  SPRFAC   = ${SPRFAC},
  PATH     = "${INPUTPATH}/",
  ATM_PATH = './',
  RSTFRQ   = ${RSTFRQ},
  RSTFMT   = ${RSTFMT},
  RSTCMP   = ${RSTCMP},
  IOTYPE   = ${IOTYPE}
/
EOF1

if ($?CWMTAG) then
cat >>! $RUNDIR/ocn_in << EOF2
 
! NAMELIST FOR CHANNEL WIDTH MODIFICATIONS
!
! CONTENTS:
!
! CWMTAG   : Array of geographical names of channels to be modified (a)
! CWMEDG   : Array of C grid cell edges to be modified. Valid options:
!            'u' or 'v' (a)
! CWMI     : Array of grid cell i-indices (i)
! CWMJ     : Array of grid cell j-indices (i)
! CWMWTH   : Array of modified grid cell widths (m) (f)
! 
&CWMOD
  CWMTAG = ${CWMTAG},
  CWMEDG = ${CWMEDG},
  CWMI   = ${CWMI},
  CWMJ   = ${CWMJ},
  CWMWTH = ${CWMWTH},
/
EOF2
endif

cat >>! $RUNDIR/ocn_in << EOF3

! BGCNML NAMELIST
!
! CONTENTS:
!
! ATM_CO2   : Atmospheric CO2 concentration [ppmv]
! DO_RIVINPT: Logical switch to activate riverine input
! DO_NDEP   : Logical switch to activate N-deposition
! NDEPFNAME : File name for atmopheric N-deposition data
&BGCNML
  ATM_CO2    = ${CCSM_CO2_PPMV}
  DO_RIVINPT = ${DO_RIVINPT}
  DO_NDEP    = ${DO_NDEP}
  NDEPFNAME  = ${NDEPFNAME}
/
EOF3

cat >>! $RUNDIR/ocn_in << EOF4

! NAMELIST FOR MERIDIONAL OVERTURNING AND FLUX REGIONS
!
! CONTENTS:
!
! MER_REGNAM : Array of region names for meridional overturning and flux
!              diagnostics (a)
! MER_REGFLG : Array of mask flags in ocean_regions.nc to be included
!              for each region (i)
! MER_MINLAT : Minimum latitude to be considered for each region (f)
! MER_MAXLAT : Maximum latitude to be considered for each region (f)
! 
&MERREG
  MER_REGNAM = 'atlantic_arctic_ocean', 'atlantic_arctic_extended_ocean', 'indian_pacific_ocean', 'global_ocean'
  MER_REGFLG(1,:) = 2, 4
  MER_REGFLG(2,:) = 2, 4, 6, 7, 8, 9
  MER_REGFLG(3,:) = 3, 5 
  MER_REGFLG(4,:) = 0
  MER_MINLAT = -34., -34., -34., -90.
  MER_MAXLAT =  90.,  90.,  90.,  90.
/

! IO-NAMELIST FOR DIAGNOSTIC OUTPUT
!
! Description:
!   BLOM supports multiple output groups for its diagnostic output.
!   Each output group is represented by one column in the namlist and may
!   have its own output format, averaging period, and file frequency.
!   The maximum number of output groups is currently limited to 10 but
!   can be changed easily in mod_dia.F.
!
!   The output precision can be choosen on a per-variable basis.
!
!   Multiple time-slices can be written to the same output file
!   provided that no variable is written in packed data format
!   (i.e. as int2 with scale factor and offset).
!
!   Compression of the output (i.e. storage of only wet points)
!   and the file format can be choosen on a per-file basis.
!
!   All time periods are specified in number of days for positive
!   integer values and fraction of day for negative integer values.
!   The length of the actual calendar month is used if 30 is written.
!   The length of the actual calendar year is used if 365 is written.
!   A variable is not written when 0 is specified.
!
! Namelist acronyms:
!   GLB_     - global parameters i.e. valid for entire output group
!   H2D_     - 2d fields with the horizontal dimensions
!   LYR_     - 3d fields with sigma layers as vertical coordinate
!   LVL_     - 3d fields with levitus leves as vertical coordinate
!   MSC_     - miscellanous, non-gridded fields
!
! Global parameters:
!   FNAMETAG - tag used in file name (c10) 
!   AVEPERIO - average period in days (i) 
!   FILEFREQ - how often to start a new file in days (i) 
!   COMPFLAG - switch for compressed/uncompressed output (i) 
!   NCFORMAT - netcdf format (valid arguments are 0 for classic,
!              1 for 64-bit offset and 2 for netcdf4/hdf5 format)
!
! Arguments for diagnostic variables:
!   0        - variable is not written
!   2        - variable is written as int2 with scale factor and offset
!   4        - variable is written as real4
!   8        - variable is written as real8
!
! Output variables:
!   ABSWND   - absolute wind speed [m s-1]
!   ALB      - surface albedo []
!   BTMSTR   - Barotropic mass streamfunction [kg s-1]
!   BRNFLX   - brine flux [kg m-2 s-1]
!   BRNPD    - brine plume depth [m]
!   DFL      - non-solar heat flux derivative [W m-2 K-1]
!   EVA      - evaporation [kg m-2 s-1]
!   FICE     - ice concentration [%]
!   FMLTFZ   - fresh water flux due to melting/freezing [kg m-2 s-1]
!   HICE     - ice thickness [m]
!   HMLTFZ   - heat flux due to melting/freezing [W m-2]
!   HSNW     - snow depth [m]
!   IAGE     - ice age [d]
!   IDKEDT   - mixed layer inertial kinetic energy tendency [kg s-3]
!   LIP      - liquid precipitation [kg m-2 s-1]
!   MAXMLD   - maximum mixed layer depth [m]
!   MLD      - mixed layer depth [m]
!   MLDU     - mixed layer depth at u-point [m]
!   MLDV     - mixed layer depth at v-point [m]
!   MLTS     - mixed layer thickness using "sigma-t" criterion [m]
!   MLTSMN   - minimum mixed layer thickness using "sigma-t" criterion [m]
!   MLTSMX   - maximum mixed layer thickness using "sigma-t" criterion [m]
!   MLTSSQ   - mixed layer thickness squared using "sigma-t" criterion [m2]
!   MTKEUS   - mixed layer TKE tendency related to friction velocity [kg s-3]
!   MTKENI   - mixed layer TKE tendency related to near inertial mot. [kg s-3]
!   MTKEBF   - mixed layer TKE tendency related to buoyancy forcing [kg s-3]
!   MTKERS   - mixed layer TKE tendency related to eddy restrat. [kg s-3]
!   MTKEPE   - mixed layer TKE tendency related to pot. energy change [kg s-3]
!   MTKEKE   - mixed layer TKE tendency related to kin. energy change [kg s-3]
!   MTY      - wind stress y-component [N m-2]
!   MXLU     - mixed layer velocity x-component [m s-1]
!   MXLV     - mixed layer velocity y-component [m s-1]
!   NSF      - non-solar heat flux [W m-2]
!   PBOT     - bottom pressure [Pa]
!   PSRF     - surface pressure [Pa]
!   RFIFLX   - frozen runoff [kg m-2 s-1]
!   RNFFLX   - liquid runoff [kg m-2 s-1]
!   SALFLX   - salt flux received by ocean [kg m-2 s-1]
!   SALRLX   - restoring salt flux received by ocean [kg m-2 s-1]
!   SBOT     - bottom salinity [g kg-1]
!   SEALV    - sea level [m]
!   SLVSQ    - sea level squared [m2]
!   SFL      - salt flux [kg m-2 s-1]
!   SOP      - solid precipitation [kg m-2 s-1]
!   SIGMX    - mixed layer density [kg m-3]
!   SSS      - ocean surface salinity [g kg-1]
!   SSSSQ    - ocean surface salinity squared [g2 kg-2]
!   SST      - ocean surface temperature [degC]
!   SSTSQ    - ocean surface temperature squared [degC2]
!   SURFLX   - heat flux received by ocean [W m-2]
!   SURRLX   - restoring heat flux received by ocean [W m-2]
!   SWA      - short-wave heat flux [W m-2]
!   T20D     - 20C isoterm depth [m]
!   TAUX     - momentum flux received by ocean x-component [N m-2]
!   TAUY     - momentum flux received by ocean y-component [N m-2]
!   TBOT     - bottom temperature [degC]
!   TICE     - ice temperature [degC]
!   TSRF     - surface temperature [degC]
!   UB       - barotropic velocity x-component [m s-1]
!   UICE     - ice velocity x-component [m s-1]
!   USTAR    - friction velocity [m s-1]
!   USTAR3   - friction velocity cubed [m3 s-3]
!   VB       - barotropic velocity y-component [m s-1]
!   VICE     - ice velocity y-component [m s-1]
!   ZTX      - wind stress x-component [N m-2]
!   BFSQ     - buoyancy frequency squared [s-1]
!   DIFDIA   - diapycnal diffusivity [log10(m2 s-1)]
!   DIFINT   - layer interface diffusivity [log10(m2 s-1)]
!   DIFISO   - isopycnal diffusivity [log10(m2 s-1)]
!   DP       - layer pressure thickness [Pa]
!   DZ       - layer thickness [m]
!   SALN     - salinity [g kg-1]
!   TEMP     - temperature [degC]
!   TRC      - tracer []
!   UFLX     - mass flux in x-direction [kg s-1]
!   UTFLX    - heat flux in x-direction [W]
!   USFLX    - salt flux in x-direction [kg s-1]
!   UMFLTD   - mass flux due to thickness diffusion in x-direction [kg s-1]
!   UTFLTD   - heat flux due to thickness diffusion in x-direction [W]
!   UTFLLD   - heat flux due to lateral diffusion in x-direction [W]
!   USFLTD   - salt flux due to thickness diffusion in x-direction [kg s-1]
!   USFLLD   - salt flux due to lateral diffusion in x-direction [kg s-1]
!   UVEL     - velocity x-component [m s-1]
!   VFLX     - mass flux in y-direction [kg s-1]
!   VTFLX    - heat flux in y-direction [W]
!   VSFLX    - salt flux in y-direction [kg s-1]
!   VMFLTD   - mass flux due to thickness diffusion in y-direction [kg s-1]
!   VTFLTD   - heat flux due to thickness diffusion in y-direction [W]
!   VTFLLD   - heat flux due to lateral diffusion in y-direction [W]
!   VSFLTD   - salt flux due to thickness diffusion in y-direction [kg s-1]
!   VSFLLD   - salt flux due to lateral diffusion in y-direction [kg s-1]
!   VVEL     - velocity x-component [m s-1]
!   WFLX     - vertical mass flux [kg s-1]
!   WFLX2    - vertical mass flux squared [kg2 s-2]
!   PV       - potential vorticity [m-1 s-1]
!   TKE      - turbulent kinetic energy [m2 s-2]
!   GLS_PSI  - generic length scale [m2 s-3]
!   IDLAGE   - ideal age [year]
!   MMFLXL   - meridional overturning circ. (MOC) on isopycnic layers [kg s-1]
!   MMFLXD   - MOC on z-levels [kg s-1]
!   MMFTDL   - MOC due to thickness diffusion on isopycnic layers [kg s-1]
!   MMFTDD   - MOC due to thickness diffusion on z-levels [kg s-1]
!   MHFLX    - meridional heat flux [W]
!   MHFTD    - meridional heat flux due to thickness diffusion [W]
!   MHFLD    - meridional heat flux due to lateral diffusion [W]
!   MSFLX    - meridional salt flux [kg s-1]
!   MSFTD    - meridional salt flux due to thickness diffusion [kg s-1]
!   MSFLD    - meridional salt flux due to lateral diffusion [kg s-1]
!   VOLTR    - section transports [kg s-1]
!   MASSGS   - global sum of mass [kg]
!   VOLGS    - global sum of volume [m3]
!   SALNGA   - global average temperature [degC]
!   TEMPGA   - global average temperature [degC]
!   SSSGA    - global average sea surface salinity [g kg-1]
!   SSTGA    - global average sea surface temperature [degC]
!
&DIAPHY
  GLB_FNAMETAG = ${GLB_FNAMETAG}, 
  GLB_AVEPERIO = ${GLB_AVEPERIO},
  GLB_FILEFREQ = ${GLB_FILEFREQ},
  GLB_COMPFLAG = ${GLB_COMPFLAG},
  GLB_NCFORMAT = ${GLB_NCFORMAT},
  H2D_ABSWND   = ${H2D_ABSWND},
  H2D_ALB      = ${H2D_ALB},
  H2D_BTMSTR   = ${H2D_BTMSTR},
  H2D_BRNFLX   = ${H2D_BRNFLX},
  H2D_BRNPD    = ${H2D_BRNPD},
  H2D_DFL      = ${H2D_DFL},
  H2D_EVA      = ${H2D_EVA},
  H2D_FICE     = ${H2D_FICE},
  H2D_FMLTFZ   = ${H2D_FMLTFZ},
  H2D_HICE     = ${H2D_HICE},
  H2D_HMLTFZ   = ${H2D_HMLTFZ},
  H2D_HSNW     = ${H2D_HSNW},
  H2D_IAGE     = ${H2D_IAGE},
  H2D_IDKEDT   = ${H2D_IDKEDT},
  H2D_LIP      = ${H2D_LIP},
  H2D_MAXMLD   = ${H2D_MAXMLD},
  H2D_MLD      = ${H2D_MLD},
  H2D_MLDU     = ${H2D_MLDU},
  H2D_MLDV     = ${H2D_MLDV},
  H2D_MLTS     = ${H2D_MLTS},
  H2D_MLTSMN   = ${H2D_MLTSMN},
  H2D_MLTSMX   = ${H2D_MLTSMX},
  H2D_MLTSSQ   = ${H2D_MLTSSQ},
  H2D_MTKEUS   = ${H2D_MTKEUS},
  H2D_MTKENI   = ${H2D_MTKENI},
  H2D_MTKEBF   = ${H2D_MTKEBF},
  H2D_MTKERS   = ${H2D_MTKERS},
  H2D_MTKEPE   = ${H2D_MTKEPE},
  H2D_MTKEKE   = ${H2D_MTKEKE},
  H2D_MTY      = ${H2D_MTY},
  H2D_MXLU     = ${H2D_MXLU},
  H2D_MXLV     = ${H2D_MXLV},
  H2D_NSF      = ${H2D_NSF},
  H2D_PBOT     = ${H2D_PBOT},
  H2D_PSRF     = ${H2D_PSRF},
  H2D_RFIFLX   = ${H2D_RFIFLX},
  H2D_RNFFLX   = ${H2D_RNFFLX},
  H2D_SALFLX   = ${H2D_SALFLX},
  H2D_SALRLX   = ${H2D_SALRLX},
  H2D_SBOT     = ${H2D_SBOT},
  H2D_SEALV    = ${H2D_SEALV},
  H2D_SLVSQ    = ${H2D_SLVSQ},
  H2D_SFL      = ${H2D_SFL},
  H2D_SOP      = ${H2D_SOP},
  H2D_SIGMX    = ${H2D_SIGMX},
  H2D_SSS      = ${H2D_SSS},
  H2D_SSSSQ    = ${H2D_SSSSQ},
  H2D_SST      = ${H2D_SST},
  H2D_SSTSQ    = ${H2D_SSTSQ},
  H2D_SURFLX   = ${H2D_SURFLX},
  H2D_SURRLX   = ${H2D_SURRLX},
  H2D_SWA      = ${H2D_SWA},
  H2D_T20D     = ${H2D_T20D},
  H2D_TAUX     = ${H2D_TAUX},
  H2D_TAUY     = ${H2D_TAUY},
  H2D_TBOT     = ${H2D_TBOT},
  H2D_TICE     = ${H2D_TICE},
  H2D_TSRF     = ${H2D_TSRF},
  H2D_UB       = ${H2D_UB},
  H2D_UICE     = ${H2D_UICE},
  H2D_USTAR    = ${H2D_USTAR},
  H2D_USTAR3   = ${H2D_USTAR3},
  H2D_VB       = ${H2D_VB},
  H2D_VICE     = ${H2D_VICE},
  H2D_ZTX      = ${H2D_ZTX},
  LYR_BFSQ     = ${LYR_BFSQ},
  LYR_DIFDIA   = ${LYR_DIFDIA},
  LYR_DIFINT   = ${LYR_DIFINT},
  LYR_DIFISO   = ${LYR_DIFISO},
  LYR_DP       = ${LYR_DP},
  LYR_DZ       = ${LYR_DZ},
  LYR_SALN     = ${LYR_SALN},
  LYR_TEMP     = ${LYR_TEMP},
  LYR_TRC      = ${LYR_TRC},
  LYR_UFLX     = ${LYR_UFLX},
  LYR_UTFLX    = ${LYR_UTFLX},
  LYR_USFLX    = ${LYR_USFLX},
  LYR_UMFLTD   = ${LYR_UMFLTD},
  LYR_UTFLTD   = ${LYR_UTFLTD},
  LYR_UTFLLD   = ${LYR_UTFLLD},
  LYR_USFLTD   = ${LYR_USFLTD},
  LYR_USFLLD   = ${LYR_USFLLD},
  LYR_UVEL     = ${LYR_UVEL},
  LYR_VFLX     = ${LYR_VFLX},
  LYR_VTFLX    = ${LYR_VTFLX},
  LYR_VSFLX    = ${LYR_VSFLX},
  LYR_VMFLTD   = ${LYR_VMFLTD},
  LYR_VTFLTD   = ${LYR_VTFLTD},
  LYR_VTFLLD   = ${LYR_VTFLLD},
  LYR_VSFLTD   = ${LYR_VSFLTD},
  LYR_VSFLLD   = ${LYR_VSFLLD},
  LYR_VVEL     = ${LYR_VVEL},
  LYR_WFLX     = ${LYR_WFLX},
  LYR_WFLX2    = ${LYR_WFLX2},
  LYR_PV       = ${LYR_PV},
  LYR_TKE      = ${LYR_TKE},
  LYR_GLS_PSI  = ${LYR_GLS_PSI},
  LYR_IDLAGE   = ${LYR_IDLAGE},
  LVL_BFSQ     = ${LVL_BFSQ},
  LVL_DIFDIA   = ${LVL_DIFDIA},
  LVL_DIFINT   = ${LVL_DIFINT},
  LVL_DIFISO   = ${LVL_DIFISO},
  LVL_DZ       = ${LVL_DZ},
  LVL_SALN     = ${LVL_SALN},
  LVL_TEMP     = ${LVL_TEMP},
  LVL_TRC      = ${LVL_TRC},
  LVL_UFLX     = ${LVL_UFLX},
  LVL_UTFLX    = ${LVL_UTFLX},
  LVL_USFLX    = ${LVL_USFLX},
  LVL_UMFLTD   = ${LVL_UMFLTD},
  LVL_UTFLTD   = ${LVL_UTFLTD},
  LVL_UTFLLD   = ${LVL_UTFLLD},
  LVL_USFLTD   = ${LVL_USFLTD},
  LVL_USFLLD   = ${LVL_USFLLD},
  LVL_UVEL     = ${LVL_UVEL},
  LVL_VFLX     = ${LVL_VFLX},
  LVL_VTFLX    = ${LVL_VTFLX},
  LVL_VSFLX    = ${LVL_VSFLX},
  LVL_VMFLTD   = ${LVL_VMFLTD},
  LVL_VTFLTD   = ${LVL_VTFLTD},
  LVL_VTFLLD   = ${LVL_VTFLLD},
  LVL_VSFLTD   = ${LVL_VSFLTD},
  LVL_VSFLLD   = ${LVL_VSFLLD},
  LVL_VVEL     = ${LVL_VVEL},
  LVL_WFLX     = ${LVL_WFLX},
  LVL_WFLX2    = ${LVL_WFLX2},
  LVL_PV       = ${LVL_PV},
  LVL_TKE      = ${LVL_TKE},
  LVL_GLS_PSI  = ${LVL_GLS_PSI},
  LVL_IDLAGE   = ${LVL_IDLAGE},
  MSC_MMFLXL   = ${MSC_MMFLXL},
  MSC_MMFLXD   = ${MSC_MMFLXD},
  MSC_MMFTDL   = ${MSC_MMFTDL},
  MSC_MMFTDD   = ${MSC_MMFTDD},
  MSC_MHFLX    = ${MSC_MHFLX},
  MSC_MHFTD    = ${MSC_MHFTD},
  MSC_MHFLD    = ${MSC_MHFLD},
  MSC_MSFLX    = ${MSC_MSFLX},
  MSC_MSFTD    = ${MSC_MSFTD},
  MSC_MSFLD    = ${MSC_MSFLD},
  MSC_VOLTR    = ${MSC_VOLTR},
  MSC_MASSGS   = ${MSC_MASSGS},
  MSC_VOLGS    = ${MSC_VOLGS},
  MSC_SALNGA   = ${MSC_SALNGA},
  MSC_TEMPGA   = ${MSC_TEMPGA},
  MSC_SSSGA    = ${MSC_SSSGA},
  MSC_SSTGA    = ${MSC_SSTGA}
/

! IO-NAMELIST FOR DIAGNOSTIC HAMOCC OUTPUT
!
! Namelist acronyms:
!   GLB_     - global parameters i.e. valid for entire output group
!   SRF_     - surface variables (includes some non-surface 2d fields)
!   FLX_     - interior ocean particle fuxes at different depth (2d)
!   INT_     - vertically integrated fields (2d)
!   LYR_     - 3d fields with sigma layers as vertical coordinate
!   LVL_     - 3d fields with levitus levels as vertical coordinate
!   SDM_     - 3d sediment fields
!   BUR_     - 2d fields of sediment burial
!
! Global parameters:
!   FNAMETAG - tag used in file name (c10) 
!   AVEPERIO - average period in days (i) 
!   FILEFREQ - how often to start a new file in days (i) 
!   COMPFLAG - switch for compressed/uncompressed output (i) 
!   NCFORMAT - netcdf format (valid arguments are 0 for classic,
!              1 for 64-bit offset and 2 for netcdf4/hdf5 format)
!   INVENTORY- how often to write an inventory of tracers to ocean 
!              output file
!  
! Arguments for diagnostic variables:
!   0        - variable is not written
!   2        - variable is written as int2 with scale factor and offset
!   4        - variable is written as real4
!   8        - variable is written as real8
!
! Output variables:
!
! Main BGC tracer fields (SFR, LYR or LVL)
!   DIC            - Dissolved carbon (dissic) [mol C m-3]
!   ALKALI         - Alkalinity (talk) [eq m-3]
!   OXYGEN         - Oxygen (o2) [mol O2 m-3]
!   ANO3           - Nitrate (no3) [mol N m-3]
!   PHOSPH         - Phosphorus (po4) [mol P m-3]
!   IRON           - Dissolved iron (dfe) [mol Fe m-3]
!   SILICA         - Silicate (si) [mol Si m-3]
!   PHYTO          - Phytoplankton (phyc) [mol C m-3]
!   NATDIC         - Natural dissolved carbon (natdissic) [mol C m-3]
!   NATALKALI      - Natural alkalinity (nattalk) [eq m-3]
!
! Other 3d tracer or diagnostic variables (LYR or LVL)
!   DP             - Layer thickness (pddpo) [m]
!   PREFO2         - preformed oxygen (p_o2) [mol O2 m-3]
!   O2SAT          - Saturated oxygen (satoxy) [mol O2 m-3]
!   PREFPO4        - preformed phosphate (p_po4) [mol PO4 m-3]
!   PREFALK        - preformed alkalinity (p_talk) [eq m-3]
!   PREFDIC        - preformed DIC (p_dic) [mol C m-3]
!   DICSAT         - saturated DIC (dic_sat) [mol C m-3]
!   POC            - Detrius (detoc) [mol C m-3]
!   CALC           - CaCO3 shells (calc) [mol C m-3]
!   OPAL           - Opal shells (opal) [mol Si m-3]
!   DOC            - Dissolved organic carbon (dissoc) [mol C m-3]
!   GRAZER         - Zooplankton (zooc) [mol C m-3]
!   PHOSY          - Primary production (pp) [mol C m-3 s-1]
!   CO3            - Carbonate ions (co3) [mol C m-3]
!   N2O            - Nitrous oxide concentration [mol N2O m-3]
!   PH             - pH (ph) [-log10([h+])]
!   OMEGAA         - Aragonite saturation state (omegaa) [1]
!   OMEGAC         - Calcite saturation state (omegac) [1]
!   NATDIC         - Natural dissolved carbon (natdissic) [mol C m-3]
!   NATALKALI      - Natural alkalinity (nattalk) [eq m-3]
!   NATCO3         - Natural carbonate ion concentration (natco3) [mol C m-3]
!   NATCALC        - Natural CaCO3 shells (natcalc) [mol C m-3]
!   NATPH          - Natural pH (natph) [-log10([h+])]
!   NATOMEGAA      - Natural aragonite saturation state (natomegaa) [1]
!   NATOMEGAC      - Natural calcite saturation state (natomegac) [1]
!   DIC13          - Dissolved C13 (dissic13) [mol C m-3]
!   DIC14          - Dissolved C14 (dissic14) [mol C m-3]
!   D13C           - delta 13C of DIC [1]
!   D14C           - delta 14C of DIC [1]
!   BIGD14C        - Delta 14C of DIC [1]
!   POC13          - Particulate organic carbon 13 (detoc13) [mol C m-3]
!   DOC13          - Dissolved organic carbon 13 (dissoc13) [mol C m-3]
!   CALC13         - Particulate inorganic carbon 13 (calc13) [mol C m-3]
!   PHYTO13        - 13C of phytoplankton biomass (phyc13) [mol C m-3]
!   GRAZER13       - 13C of zootoplankton biomass (zooc13) [mol C m-3]
!   CFC11          - CFC11 concentration [mol CFC11 m-3]
!   CFC12          - CFC12 concentration [mol CFC12 m-3]
!   SF6            - SF6 concentration [mol SF6 m-3]
!   NOS            - Number of sinking particles (aggregate scheme, nos) [cm-3]
!   WPHY           - Mass sinking velocity (aggregate scheme) [m d-1]
!   WNOS           - Number sinking velocity (aggregate scheme) [m d-1]
!   EPS            - Epsilon exponent (aggregate scheme) [1]
!   ASIZE          - Average particle size (aggregate scheme)
!
! 2d-fields (SFR)
!   EXPORT         - Export production (epc100) [mol C m-2 s-1]
!   EXPOCA         - Ca export production (epcalc100) [mol Ca m-2 s-1]
!   EXPOSI         - Si export production (epsi100) [mol Si m-2 s-1]
!   PCO2           - Surface PCO2 (spco2) [uatm]
!   KWCO2          - kwco2 x solubility
!   CO2FXD         - Downward CO2 flux (co2fxd) [kg C m-2 s-1]
!   CO2FXU         - Upward CO2 flux (co2fxu) [kg C m-2 s-1]
!   NIFLUX         - Nitrogen flux (fgn2) [mol N2 m-2 s-1]
!   OXFLUX         - Oxygen flux (fgo2) [mol O2 m-2 s-1]
!   N2OFX          - Nitrous oxide flux [mol N2O m-2 s-1]
!   DMSFLUX        - DMS flux (dmsflux) [mol DMS m-2 s-1]
!   DMS            - surface DMS concentration (dms) [mol DMS m-3]
!   DMSPROD        - DMS production (dmsprod) [mol DMS m-2 s-1]
!   DMS_BAC        - DMS bacterial consuption (dms_bac) [mol DMS m-2 s-1]
!   DMS_UV         - DMS decomposition by UV (dms_uv) [mol DMS m-2 s-1]
!   ATMCO2         - Atmospheric CO2 (atmco2) [ppm]
!   ATMO2          - Atmospheric O2 (atmo2) [ppm]
!   ATMN2          - Atmospheric N2 (atmn2) [ppm]
!   NATPCO2        - Natural surface PCO2 (spco2) [uatm]
!   NATCO2FX       - Natural net CO2 flux (natco2fx) [kg C m-2 s-1]
!   CO213FXD       - Downward 13CO2 flux (co213fxd) [kg C m-2 s-1]
!   CO213FXU       - Upward 13CO2 flux (co213fxu) [kg C m-2 s-1]
!   CO214FXD       - Downward 14CO2 flux (co214fxd) [kg C m-2 s-1]
!   CO214FXU       - Upward 14CO2 flux (co214fxu) [kg C m-2 s-1]
!   CFC11          - CFC11 flux [mol CFC11 m-2 s-1]
!   CFC12          - CFC12 flux [mol CFC12 m-2 s-1]
!   SF6            - SF6 flux [mol SF6 m-2 s-1]
!
! Vertically integrated fields (INT)
!   PHOSY          - Vertically integrated primary production [mol C m-3 s-1]
!   NFIX           - Vertically integrated nitrogen fixation
!   DNIT           - Vertically integrated denitrification
!
! Particle fluxes (FLX, where ****=0100,0500,1000,2000,4000, or _BOT)
!   CARFLX****     - POC flux at **** metres depth [mol C m-2 s-1]
!   BSIFLX****     - Biogenic silica flux at **** metres depth [mol Si m-2 s-1]
!   CALFLX****     - Calcium carbonate flux at **** metres depth [mol C m-2 s-1]
!
! Sediment fields (SDM)
!   POWAIC         - (powdic) [mol C m-3]
!   POWAAL         - (powalk) [eq m-3]
!   POWAPH         - (powpho) [eq m-3]
!   POWAOX         - (powox) [mol O2 m-3]
!   POWN2          - (pown2) [mol N2 m-3]
!   POWNO3         - (powno3)[mol N m-3]
!   POWASI         - (powsi) [mol Si m-3]
!   SSSO12         - (ssso12) [mol m-3]
!   SSSSIL         - (ssssil) [mol Si m-3]
!   SSSC12         - (sssc12) [mol C m-3]
!   SSSTER         - (ssster) [mol m-3]
!
! Burial fields (BUR)
!   SSSO12         - Solid sediment organic carbon [mol P m-2]
!   SSSSIL         - Solid sediment silica [mol Si m-2]
!   SSSC12         - Solid sediment inorganic carbon [mol C m-2]
!   SSSTER         - 
!
&DIABGC
  GLB_FNAMETAG       = ${BGC_FNAMETAG},
  GLB_AVEPERIO       = ${BGC_AVEPERIO},
  GLB_FILEFREQ       = ${BGC_FILEFREQ},
  GLB_COMPFLAG       = ${BGC_COMPFLAG},
  GLB_NCFORMAT       = ${BGC_NCFORMAT},
  GLB_INVENTORY      = ${BGC_INVENTORY},
  SRF_PHOSPH         = ${SRF_PHOSPH},
  SRF_OXYGEN         = ${SRF_OXYGEN}, 
  SRF_IRON           = ${SRF_IRON},    
  SRF_ANO3           = ${SRF_ANO3}, 
  SRF_ALKALI         = ${SRF_ALKALI},
  SRF_SILICA         = ${SRF_SILICA}, 
  SRF_DIC            = ${SRF_DIC},
  SRF_PHYTO          = ${SRF_PHYTO},
  SRF_EXPORT         = ${SRF_EXPORT},
  SRF_EXPOSI         = ${SRF_EXPOSI},
  SRF_EXPOCA         = ${SRF_EXPOCA},
  SRF_KWCO2          = ${SRF_KWCO2},
  SRF_PCO2           = ${SRF_PCO2},
  SRF_CO2FXD         = ${SRF_CO2FXD},
  SRF_CO2FXU         = ${SRF_CO2FXU},
  SRF_OXFLUX         = ${SRF_OXFLUX},
  SRF_NIFLUX         = ${SRF_NIFLUX},
  SRF_N2OFX          = ${SRF_N2OFX},
  SRF_DMSFLUX        = ${SRF_DMSFLUX},
  SRF_DMS            = ${SRF_DMS},
  SRF_DMSPROD        = ${SRF_DMSPROD},
  SRF_DMS_BAC        = ${SRF_DMS_BAC},
  SRF_DMS_UV         = ${SRF_DMS_UV},
  SRF_ATMCO2         = ${SRF_ATMCO2},
  SRF_ATMO2          = ${SRF_ATMO2},
  SRF_ATMN2          = ${SRF_ATMN2},
  SRF_NATDIC         = ${SRF_NATDIC},
  SRF_NATALKALI      = ${SRF_NATALKALI},
  SRF_NATPCO2        = ${SRF_NATPCO2},
  SRF_NATCO2FX       = ${SRF_NATCO2FX},
  SRF_CO213FXD       = ${SRF_CO213FXD}, 
  SRF_CO213FXU       = ${SRF_CO213FXU},
  SRF_CO214FXD       = ${SRF_CO214FXD},
  SRF_CO214FXU       = ${SRF_CO214FXU},
  SRF_CFC11          = ${SRF_CFC11},
  SRF_CFC12          = ${SRF_CFC12},
  SRF_SF6            = ${SRF_SF6},
  INT_PHOSY          = ${INT_PHOSY},
  INT_NFIX           = ${INT_NFIX},
  INT_DNIT           = ${INT_DNIT},
  FLX_CAR0100        = ${FLX_CAR0100},
  FLX_CAR0500        = ${FLX_CAR0500},
  FLX_CAR1000        = ${FLX_CAR1000},
  FLX_CAR2000        = ${FLX_CAR2000},
  FLX_CAR4000        = ${FLX_CAR4000},
  FLX_CAR_BOT        = ${FLX_CAR_BOT},
  FLX_BSI0100        = ${FLX_BSI0100},
  FLX_BSI0500        = ${FLX_BSI0500},
  FLX_BSI1000        = ${FLX_BSI1000},
  FLX_BSI2000        = ${FLX_BSI2000},
  FLX_BSI4000        = ${FLX_BSI4000},
  FLX_BSI_BOT        = ${FLX_BSI_BOT},
  FLX_CAL0100        = ${FLX_CAL0100},
  FLX_CAL0500        = ${FLX_CAL0500},
  FLX_CAL1000        = ${FLX_CAL1000},
  FLX_CAL2000        = ${FLX_CAL2000},
  FLX_CAL4000        = ${FLX_CAL4000},
  FLX_CAL_BOT        = ${FLX_CAL_BOT},
  LYR_PHYTO          = ${LYR_PHYTO},
  LYR_GRAZER         = ${LYR_GRAZER},
  LYR_DOC            = ${LYR_DOC},
  LYR_PHOSY          = ${LYR_PHOSY},
  LYR_PHOSPH         = ${LYR_PHOSPH},
  LYR_OXYGEN         = ${LYR_OXYGEN},
  LYR_IRON           = ${LYR_IRON},
  LYR_ANO3           = ${LYR_ANO3},
  LYR_ALKALI         = ${LYR_ALKALI},
  LYR_SILICA         = ${LYR_SILICA},
  LYR_DIC            = ${LYR_DIC},
  LYR_POC            = ${LYR_POC},
  LYR_CALC           = ${LYR_CALC},
  LYR_OPAL           = ${LYR_OPAL},
  LYR_CO3            = ${LYR_CO3},
  LYR_N2O            = ${LYR_N2O},
  LYR_PH             = ${LYR_PH},
  LYR_OMEGAC         = ${LYR_OMEGAC},
  LYR_OMEGAA         = ${LYR_OMEGAA},
  LYR_PREFO2         = ${LYR_PREFO2},
  LYR_O2SAT          = ${LYR_O2SAT},
  LYR_PREFPO4        = ${LYR_PREFPO4},
  LYR_PREFALK        = ${LYR_PREFALK},
  LYR_PREFDIC        = ${LYR_PREFDIC},
  LYR_DICSAT         = ${LYR_DICSAT},
  LYR_NATDIC         = ${LYR_NATDIC},
  LYR_NATALKALI      = ${LYR_NATALKALI},
  LYR_NATCO3         = ${LYR_NATCO3},
  LYR_NATCALC        = ${LYR_NATCALC},
  LYR_NATPH          = ${LYR_NATPH},
  LYR_NATOMEGAC      = ${LYR_NATOMEGAC},
  LYR_NATOMEGAA      = ${LYR_NATOMEGAA},
  LYR_DIC13          = ${LYR_DIC13},
  LYR_DIC14          = ${LYR_DIC14},
  LYR_D13C           = ${LYR_D13C},
  LYR_D14C           = ${LYR_D14C},
  LYR_BIGD14C        = ${LYR_BIGD14C},
  LYR_POC13          = ${LYR_POC13},
  LYR_DOC13          = ${LYR_DOC13},
  LYR_CALC13         = ${LYR_CALC13},
  LYR_PHYTO13        = ${LYR_PHYTO13},
  LYR_GRAZER13       = ${LYR_GRAZER13},
  LYR_CFC11          = ${LYR_CFC11},
  LYR_CFC12          = ${LYR_CFC12},
  LYR_SF6            = ${LYR_SF6},
  LYR_NOS            = ${LYR_NOS},
  LYR_WPHY           = ${LYR_WPHY},
  LYR_WNOS           = ${LYR_WNOS},
  LYR_EPS            = ${LYR_EPS},
  LYR_ASIZE          = ${LYR_ASIZE},
  LYR_DP             = ${BGC_DP},
  LVL_PHYTO          = ${LVL_PHYTO},
  LVL_GRAZER         = ${LVL_GRAZER},
  LVL_DOC            = ${LVL_DOC},
  LVL_PHOSY          = ${LVL_PHOSY},
  LVL_PHOSPH         = ${LVL_PHOSPH},
  LVL_OXYGEN         = ${LVL_OXYGEN},
  LVL_IRON           = ${LVL_IRON},
  LVL_ANO3           = ${LVL_ANO3},
  LVL_ALKALI         = ${LVL_ALKALI},
  LVL_SILICA         = ${LVL_SILICA},
  LVL_DIC            = ${LVL_DIC},
  LVL_POC            = ${LVL_POC},
  LVL_CALC           = ${LVL_CALC},
  LVL_OPAL           = ${LVL_OPAL},
  LVL_CO3            = ${LVL_CO3},
  LVL_N2O            = ${LVL_N2O},
  LVL_PH             = ${LVL_PH},
  LVL_OMEGAC         = ${LVL_OMEGAC},
  LVL_OMEGAA         = ${LVL_OMEGAA},
  LVL_PREFO2         = ${LVL_PREFO2},
  LVL_O2SAT          = ${LVL_O2SAT},
  LVL_PREFPO4        = ${LVL_PREFPO4},
  LVL_PREFALK        = ${LVL_PREFALK},
  LVL_PREFDIC        = ${LVL_PREFDIC},
  LVL_DICSAT         = ${LVL_DICSAT},
  LVL_NATDIC         = ${LVL_NATDIC},
  LVL_NATALKALI      = ${LVL_NATALKALI},
  LVL_NATCO3         = ${LVL_NATCO3},
  LVL_NATCALC        = ${LVL_NATCALC},
  LVL_NATPH          = ${LVL_NATPH},
  LVL_NATOMEGAC      = ${LVL_NATOMEGAC},
  LVL_NATOMEGAA      = ${LVL_NATOMEGAA},
  LVL_DIC13          = ${LVL_DIC13},
  LVL_DIC14          = ${LVL_DIC14},
  LVL_D13C           = ${LVL_D13C},
  LVL_POC13          = ${LVL_POC13},
  LVL_DOC13          = ${LVL_DOC13},
  LVL_CALC13         = ${LVL_CALC13},
  LVL_PHYTO13        = ${LVL_PHYTO13},
  LVL_GRAZER13       = ${LVL_GRAZER13},
  LVL_CFC11          = ${LVL_CFC11},
  LVL_CFC12          = ${LVL_CFC12},
  LVL_SF6            = ${LVL_SF6},
  LVL_NOS            = ${LVL_NOS},
  LVL_WPHY           = ${LVL_WPHY},
  LVL_WNOS           = ${LVL_WNOS},
  LVL_EPS            = ${LVL_EPS},
  LVL_ASIZE          = ${LVL_ASIZE},
  SDM_POWAIC         = ${SDM_POWAIC},
  SDM_POWAAL         = ${SDM_POWAAL},
  SDM_POWAPH         = ${SDM_POWAPH},
  SDM_POWAOX         = ${SDM_POWAOX},
  SDM_POWN2          = ${SDM_POWN2},
  SDM_POWNO3         = ${SDM_POWNO3},
  SDM_POWASI         = ${SDM_POWASI},
  SDM_SSSO12         = ${SDM_SSSO12},
  SDM_SSSSIL         = ${SDM_SSSSIL},
  SDM_SSSC12         = ${SDM_SSSC12},
  SDM_SSSTER         = ${SDM_SSSTER},
  BUR_SSSO12         = ${BUR_SSSO12},
  BUR_SSSSIL         = ${BUR_SSSSIL},
  BUR_SSSC12         = ${BUR_SSSC12},
  BUR_SSSTER         = ${BUR_SSSTER}
/
EOF4
